<?xml version="1.0" encoding="UTF-8"?>
<!--
	IVY
	
	Copyright 2021-2024 MicroEJ Corp. All rights reserved.
	Use of this source code is governed by a BSD-style license that can be found with this software.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:m="http://ant.apache.org/ivy/maven" xmlns:ej="https://developer.microej.com" ej:version="2.0.0"> 

	<info organisation="com.microej.veeport.st.stm32f7508-dk.validation-reports" module="security-testsuite-report" status="integration" revision="2.3.0">
        <ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-testsuite" revision="[2.2.0-RC0,3.0.0-RC0["/>
	</info>
    
    <configurations>
    	<conf name="default" />
    	<conf name="provided" />
    	<conf name="build-test" visibility="private" />
    	<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
    </configurations>

    <publications>
    </publications>
    
    <dependencies>
    	<!-- 
    		The testsuite module dependency (i.e. module that contains tests).
    		The last module version is automatically fetched by default.
    		To freeze the module version, add the following attribute: ej:match="perfect"    	
    	-->
			<dependency org="com.microej.pack.net" name="security-1_7-testsuite" rev="1.7.0"  conf="test->default;provided->provided" />
    </dependencies>
</ivy-module>
